### ISSUE TITLE
Automatically configure venv for users

### ISSUE THREAD

**Issue by iloveitaly** [asdf-community/asdf-uv#22]
**Is your feature request related to a problem? Please describe.**

Nope.

**Describe the solution you'd like**

What do you think about automatically setting up a venv for users? Like this:

https://github.com/mise-plugins/mise-poetry/blob/main/bin/exec-env

We can detect when `uv.lock` exists and run a similar setup command.

**Comment by b1-luettje** [comment]
Hey (:

I'd rather have this plugin only install `uv` and nothing else. There are lots of other tools that are better suited for this task, `direnv` for example. @hynek has an example at https://hynek.me/articles/docker-uv#local-development
